config/routes.rb
Rails.application.routes.draw do
  root 'goals#index'
  resources :goals do
    resources :tasks, only: [:show, :new, :edit]
  end
  get '/garden' => 'goals#garden'
  resources :tasks

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :goal
  validates_presence_of :name
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :goal_categories
  has_many :goals, through: :goal_categories

  validates_uniqueness_of :name
  #validates :name, length: {maximum: 20}

  def subcategory
    subcategory = "none"
    self.goal_categories.each do |goal_category|
      if goal_category.subcategory != "" && !goal_category.subcategory.nil?
        subcategory = goal_category.subcategory
      end
    end
    subcategory
  end

end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :goal_categories
  has_many :categories, through: :goal_categories
  has_many :tasks, dependent: :delete_all

  #validation
  validates_presence_of :name, :start_date, :end_date
  validates :name, length: {maximum: 30}
  validate :date_in_future


  #scope methods
  scope :complete, -> {where(status: 'Complete')}
  scope :incomplete, -> {where.not(status: 'Complete')}
  scope :in_progress, -> {where(status: 'In Progress')}


  #accepts_nested_attributes_for :categories, reject_if: :all_blank
  accepts_nested_attributes_for :tasks, reject_if: :all_blank
  accepts_nested_attributes_for :goal_categories

  def categories_attributes=(category_attributes)
    category_attributes.values.each do |category_attribute|
      if category_attribute[:name] != "" && !category_attribute[:name].nil?
        category = Category.find_or_create_by(name: category_attribute[:name])
        self.categories << category
      end
    end
  end

  def goal_categories_attributes=(goal_categories_attributes)
    goal_categories_attributes.values.each do |goal_category_attribute|
      if goal_category_attribute[:subcategory] != "" && !goal_category_attribute[:subcategory].nil?
        goal_category = GoalCategory.find_or_create_by(goal_category_attribute)
        self.goal_categories << goal_category
      end
    end
  end


  #progress method
  def progress
    total = self.tasks.count
    current = self.tasks.complete.count
    progress = current / total .to_f
    percent = progress * 100
    percent
  end

  #plant_image method
  def plant_image
    if self.tasks.empty?
      if self.status == "Incomplete"
        "stage-1"
      elsif self.status == "In Progress"
        "stage-3"
      elsif self.status == "Complete"
        "stage-5"
      end
    else
      if self.progress.between?(0,25)
        "stage-1"
      elsif self.progress.between?(26,50)
        "stage-2"
      elsif self.progress.between?(51,75)
        "stage-3"
      elsif self.progress.between?(75,99)
        "stage-4"
      else
        "stage-5"
      end
    end
  end

  #validate date
  def date_in_future
    if !self.end_date.future?
      errors.add(:end_date, "Date must be in the future.")
    end
  end

end

app/models/goal_category.rb
class GoalCategory < ApplicationRecord
  belongs_to :goal
  belongs_to :category


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :goal
  validates_presence_of :name

  #scope methods
  scope :complete, -> {where(status: 'Complete')}
  scope :incomplete, -> {where.not(status: 'Complete')}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

  has_many :goals
  has_many :tasks, through: :goals

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
       #binding.pry
        user.provider = auth.provider
        user.uid = auth.uid
       #user.email = auth.info.email
        user.name = auth.info.name
        user.password = Devise.friendly_token[0,20]
      end
  end

  def most_completed_tasks
    most = self.goals.first.tasks.complete.count
    @goal_with_most = self.goals.first
    self.goals.each do |goal|
      if goal.tasks.complete.count > most
        @goal_with_most = goal
      end
    end
    @goal_with_most
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  helper_method :most_completed_tasks

  def most_completed_tasks
    @user = current_user
    @user.most_completed_tasks
  end

  def index
    #TODO change this so that it's only the user's goals
    @goals = current_user.goals.incomplete
  end

  def garden
    @goals = current_user.goals.complete
  end

  def new
    @goal = Goal.new
    @goal.categories.build
    @goal.goal_categories.build
    @goal.tasks.build(name: "Task 1")
    @goal.tasks.build(name: "Task 2")
    @goal.tasks.build(name: "Task 3")
  end

  def create
    @goal = current_user.goals.build(goal_params)
    if @goal.save
      flash[:notice] = "Goal successfully created!"
      redirect_to goal_path(@goal)
    else
      render :new
    end
  end

  def show
    if current_user == @goal.user
      @tasks = @goal.tasks
    else
      redirect_to '/'
    end
  end

  def edit
    if current_user == @goal.user
      @tasks = @goal.tasks
    else
      redirect_to '/'
    end
  end

  def update
    if @goal.update(goal_params)
      flash[:notice] = "Goal successfully updated!"
      redirect_to goal_path(@goal)
    else
      render :edit
    end
  end

  def destroy
    if current_user == @goal.user
      @goal.destroy
      flash[:notice] = "Goal successfully deleted!"
      redirect_to '/'
    else
      redirect_to '/'
    end
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
  end

  def goal_params
    params.require(:goal).permit(:name, :description, :status, :start_date, :end_date, category_ids:[], categories_attributes:[:name], goal_categories_attributes:[:subcategory, :category_id], tasks_attributes:[:name, :description])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.incomplete
  end

  def new
    @task = Task.new(goal_id: params[:goal_id])
  end

  def create
    @goal = Goal.find_by_id(params[:task][:goal_id])
    @task = @goal.tasks.build(task_params)
    if @task.save
      flash[:notice] = "Task successfully created!"
      redirect_to goal_path(@goal)
    else
      render :new
    end
  end

  def show
  end

  def edit
    if current_user == @task.goal.user
      render :edit
    else
      redirect_to '/'
    end
  end

  def update
    @goal = Goal.find_by_id(params[:task][:goal_id])
    if @task.update(task_params)
      flash[:notice] = "Task successfully updated!"
      redirect_to goal_path(@goal)
    else
      render :edit
    end
  end

  #add notices about deleted task
  def destroy
    if current_user == @task.goal.user
      @task.destroy
      flash[:notice] = "Task successfully deleted!"
      redirect_to '/'
    else
      redirect_to '/'
    end
  end

  private

  def set_task
    @task = Task.find_by_id(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :status, :description, :goal_id)
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>
  <fieldset>
    <% if @goal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @goal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div><br>
    <% end %>

    <div class="field form-group row grow-form">
      <%= f.label :name %>
      <%= f.text_field :name, :class => 'form-control'%><br>
    </div>

    <div class="field form-group row grow-form">
      <%= f.label :description %>
      <%= f.text_area :description, :class => 'form-control' %><br>
    </div>

    <br>

    <div class="field form-group grow-form">
      <%= f.label :status %>
      <%= f.select :status, options_for_select([["Incomplete", "Incomplete"], ["In Progress", "In Progress"], ["Complete", "Complete"]]), :class => 'form-control' %>
    </div>

    <div class="field form-group grow-form">
      <%= f.label :start_date %>
      <%= f.date_select :start_date, :class => 'form-control' %><br>
    </div>

    <div class="field form-group grow-form">
      <%= f.label :end_date %>
      <%= f.date_select :end_date, :class => 'form-control' %><br>
    </div>

    <br>

    <div class="field form-group grow-form">
      <h4>Choose a Category:</h4><br>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, :class => 'form-control' %><br>
    </div>

    <h4>Or, Create a New Category:</h4>
    <div class="field form-group row grow-form">
      <%= f.fields_for :categories, @goal.categories.build do |category_fields| %>
        <%= category_fields.label :name %>
        <%= category_fields.text_field :name, :class => 'form-control' %><br>
      <% end %>
    </div>

    <h4>Create A Subcategory:</h4>
    <div class="field form-group row grow-form">
      <%= f.fields_for :goal_categories, @goal.goal_categories.build do |goal_category_fields| %>
        <%= goal_category_fields.label :category %>
        <%= goal_category_fields.collection_select :category_id, Category.all, :id, :name, :class => 'form-control' %>
        <%= goal_category_fields.label :subcategory %>
        <%= goal_category_fields.text_field :subcategory %>
      <% end %>
    </div>

    <h4>Add Tasks:</h4>
    <p>To start, set 3 tasks that you can take to achieve your goal. Don't worry! You can add more later if you wish.</p>

    <hr>
    <div class="field form-group grow-form goal-task-form">
      <h5 class="task-label">Task #1:</h5>
      <%= f.fields_for :tasks, @goal.tasks.build do |task_fields| %>
        <%= task_fields.label :name %>
        <%= task_fields.text_field :name, :class => 'form-control' %><br>
        <%= task_fields.label :description %>
        <%= task_fields.text_field :description, :class => 'form-control' %><br>
      <% end %>
    </div>

    <hr>
    <div class="field form-group grow-form goal-task-form">
      <h5 class="task-label">Task #2:</h5>
      <%= f.fields_for :tasks, @goal.tasks.build do |task_fields| %>
        <%= task_fields.label :name %>
        <%= task_fields.text_field :name, :class => 'form-control' %><br>
        <%= task_fields.label :description %>
        <%= task_fields.text_field :description, :class => 'form-control' %><br>
      <% end %>
    </div>

    <hr>
    <div class="field form-group grow-form goal-task-form">
      <h5 class="task-label">Task #3:</h5>
      <%= f.fields_for :tasks, @goal.tasks.build do |task_fields| %>
        <%= task_fields.label :name%>
        <%= task_fields.text_field :name, :class => 'form-control' %><br>
        <%= task_fields.label :description %>
        <%= task_fields.text_field :description, :class => 'form-control' %><br>
      <% end %>
    </div><br>

    <div class="actions">
      <%= f.submit :class => 'btn btn-success' %>
    </div>
  </fieldset>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit Your Goal</h1>
<%= render 'form' %>

app/views/goals/garden.html.erb
<h1>Welcome to Your Garden</h1>
<p>Here you can see all the past goals that you have accomplished.</p>
<div class="goal-box">
  <% @goals.each do |goal| %>
    <div class="goal">
      <%= image_tag("plant-#{goal.plant_image}", width: "100") %>
      <h3><%= link_to goal.name, goal_path(goal) %></h3>
    </div>
  <% end %>
</div>

app/views/goals/index.html.erb
<h1>Welcome, <%= current_user.email %></h1>
<h5>Here is your Goal with the most completed tasks!</h5>
<div>
  <h3><%= current_user.most_completed_tasks.name %></h3>
</div>

<div class="goal-box">
  <% @goals.each do |goal| %>
    <div class="goal">
      <%= image_tag("plant-#{goal.plant_image}", width: "100") %>
      <h3><%= link_to goal.name, goal_path(goal) %></h3>
      <div class="progress">
        <div class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" aria-valuenow="<%= goal.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= goal.progress %>%"></div>
      </div>
    </div>
  <% end %>
</div>

<div class="btn btn-success button">
  <%= link_to "New Goal", new_goal_path(@goal) %>
</div><br>

app/views/goals/new.html.erb
<h1>Grow a New Goal!</h1>
<%= render 'form'%>

app/views/goals/show.html.erb
<div class="back-button">
  <p>&#8592;</p>
  <%= link_to 'Back to Home', root_path%>
</div>
<div id="show-goal">

<!-- INFO ROW -->
  <div class="row goal-info">

    <!-- LEFT SIDE -->
    <div class="left-goal-box">
      <h1 id="goal-name">Goal: <%= @goal.name %></h1>

      <div class="progress goal-bar">
        <div class="progress-bar progress-bar-striped bg-success progress-bar-animated" role="progressbar" aria-valuenow="<%= @goal.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @goal.progress %>%"></div>
      </div>
      <br>

      <p><%= @goal.description %></p>
      <p class="status status-<%= @goal.status %>"><%= @goal.status %></p>

      <% if !@goal.categories.empty? %>
        <div class="category">
          <h6>CATEGORY: </h6>
          <% @goal.categories.uniq.each do |c| %>
            <h6><%= c.name %>
              (Subcategory:
              <%= c.subcategory %>
              )</h6><br>
          <% end %>
        </div>
      <% end %>

      <% if @goal.status != "Complete" %>
        <h3><%= distance_of_time_in_words(Date.current, @goal.end_date).capitalize%>&nbsp; Remaining</h3>
      <% end %>


    </div>
    <!-- END OF LEFT SIDE -->

    <!-- RIGHT SIDE -->
    <div class="right-goal-box">
      <%= image_tag("plant-#{@goal.plant_image}", width: "200") %>
        <div class="goal-buttons">
          <div class="btn btn-info button">
            <%= link_to "Edit Goal", edit_goal_path(@goal) %>
          </div>

          <div class="btn btn-danger button">
            <%= link_to "Delete Goal", goal_path(@goal), method: :delete %>
          </div>
        </div>
      </div>
    <!-- END OF RIGHT SIDE -->

  </div>
<!-- END OF INFO ROW-->

  <hr>

<!-- TASKS ROW -->
  <h3>Tasks:</h3>
  <div class="goal-tasks row">
    <div class="task-box">
      <% @goal.tasks.each do |a| %>
      <%= link_to a.name, task_path(a), :class => 'task' %>
      <% end %>
    </div>
  </div>
<!-- END OF TASKS ROW -->

  <div class="btn btn-success button">
    <%= link_to "New Task", new_goal_task_path(@goal) %>
  </div><br>
</div>

app/views/home/index.html.erb
<div class="home-container">
  <span class="home-button"><%= link_to "Sign Up", new_user_registration_path %></span>
  <span class="home-button"><%= link_to "Log In", new_user_session_path %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grow Your Goals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.2/lumen/bootstrap.min.css" rel="stylesheet" integrity="sha384-rGAkR2qts0FfeepPEwAKdA+KLiTct+OBJ7ukPPivL86aKZa39nuOS0Yj6Sy8ebLR" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <header>
        <!-- Logo -->
        <%= image_tag("Logo-Grow.svg", width: '800px', id: 'main-logo') %>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id="main-menu">
          <div class="" id="navbarColor03">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to('Home', root_path)  %>
              </li>
              <li class="nav-item">
                <%= link_to('Garden', '/garden') %>
              </li>
              <li class="nav-item">
                <%= link_to('Tasks', tasks_path)  %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to('Login', new_user_session_path)  %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </header>

      <!-- Main -->
      <main role="main" class="main-container">

        <% if flash[:notice] %>
            <div class="alert alert-dismissible alert-success notice">
              <strong>Oh snap! </strong><%= flash[:notice] %>
            </div>
        <% end %>

        <%= yield %>

      </main>

      <!-- Footer -->
      <footer>
          <div id="footer-left"><p>Copyright &copy; 2017 <a href="http://jennimacklin.com">Jenni Macklin</a></p></div>
          <div id="footer-right"><p>Created as part of the <a href="https://flatironschool.com">Learn.Co</a> curriculum</p></div>
      </footer>
  </div>


  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :goal_id %>

  <div class="field form-group row grow-form">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  </div><br>

  <div class="field form-group row grow-form">
    <%= f.label :description %>
    <%= f.text_field :description, :class => 'form-control' %>
  </div><br>


  <div class="field form-group row grow-form">
    <%= f.label :status %>
    <%= f.select :status, options_for_select([["Incomplete", "Incomplete"], ["Complete", "Complete"]]), :class => 'form-control'  %>
  </div>

  <div class="actions">
    <%= f.submit  :class => 'btn btn-success' %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>

<div class="task-box">
  <% @tasks.each do |a| %>
    <%= link_to a.name, task_path(a), :class => 'task' %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="back-button">
  <p>&#8592;</p>
  <%= link_to 'Back to Goal', goal_path(@task.goal)%>
</div>

<h1><%= @task.name %></h1>
<h4><%= @task.status %></h4>
<p><%= @task.description %></p>
<div class="btn btn-info button">
  <%= link_to "Edit Task", edit_goal_task_path(@task) %>
</div>

<div class="btn btn-danger button">
  <%= link_to "Delete Task", task_path(@task), method: :delete %>
</div>